---
title: "repeat_analysis"
author: "gmoney$$"
date: "5/27/2020"
output: pdf_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
library(knitr)
library(tidyverse)
library(bsseq)
library(Biostrings)
library(ggplot2)
library(png)
library(cowplot)
library(circlize)
options(scipen=999)
options(knitr.duplicate.label = 'allow')
```



```{r r fig.width=12, fig.height=4}

#cov <- read_tsv(params$cov, col_names = F)


repeats1 <- read_tsv("/uru/Data/Nanopore/projects/moth/2020_analysis/annotation/repeats/repeatmasker/merged/moth_canu_nanopolish_racon1.FINAL.fasta_forplot.tsv", col_names = F)

repeats2 <- read_tsv("/uru/Data/Nanopore/projects/moth/2020_analysis/annotation/repeats/repeatmasker/merged/moth_canu_nanopolish_racon1.FINAL.fasta.masked_forplot.tsv", col_names = F)

size=470051811

repeats <- rbind(repeats1, repeats2)

list=array("snRNA" ,"srpRNA" , "tRNA" , "rRNA" )
repeat_meta <- repeats %>%
  mutate(bases = (X3-X2)) %>%
  separate(X5, c("class", "family"), sep =  "/") %>%
  mutate(class = gsub("\\?", "", class)) %>%
  mutate(class = str_replace(class, "snRNA" , "small_RNA")) %>%
  mutate(class = str_replace(class, "srpRNA" , "small_RNA")) %>%
  mutate(class = str_replace(class, "tRNA" , "small_RNA")) %>% 
  mutate(class = str_replace(class, "rRNA" , "small_RNA")) %>%
  group_by(class) %>%
  summarize(total = sum(bases)) %>%
  mutate(percent = (total/size)*100)



```





```{r fig.width=12, fig.height=4}


library(viridis)
count.data <- repeat_meta %>%
  arrange(desc(class)) %>%
  mutate(lab.ypos = cumsum(percent) - 0.5*percent) %>%
  mutate(percent = round(percent, digits = 2))
count.data

ggplot(count.data, aes(x = "", y = percent, fill = class)) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0)+
  geom_text(aes(y = lab.ypos, label = percent), color = "white")+
  #scale_fill_manual(values = mycols) +
  theme_void()+scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) 

```