---
title: "repeat_analysis"
author: "gmoney$$"
date: "5/27/2020"
output: pdf_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE)
library(knitr)
library(tidyverse)
library(bsseq)
library(Biostrings)
library(ggplot2)
library(png)
library(cowplot)
library(circlize)
options(scipen=999)
options(knitr.duplicate.label = 'allow')
```



```{r r fig.width=12, fig.height=4}

#cov <- read_tsv(params$cov, col_names = F)


repeats1 <- read_tsv("/uru/Data/Nanopore/projects/moth/2020_analysis/annotation/repeats/repeatmasker/merged/moth_canu_nanopolish_racon1.FINAL.fasta_forplot.tsv", col_names = F)

repeats2 <- read_tsv("/uru/Data/Nanopore/projects/moth/2020_analysis/annotation/repeats/repeatmasker/merged/moth_canu_nanopolish_racon1.FINAL.fasta.masked_forplot.tsv", col_names = F)

size=470051811

repeats <- rbind(repeats1, repeats2)

list=array("snRNA" ,"srpRNA" , "tRNA" , "rRNA" )
repeat_meta <- repeats %>%
  mutate(bases = (X3-X2)) %>%
  separate(X5, c("class", "family"), sep =  "/") %>%
  mutate(class = gsub("\\?", "", class)) %>%
  mutate(class = str_replace(class, "snRNA" , "small_RNA")) %>%
  mutate(class = str_replace(class, "srpRNA" , "small_RNA")) %>%
  mutate(class = str_replace(class, "tRNA" , "small_RNA")) %>% 
  mutate(class = str_replace(class, "rRNA" , "small_RNA")) %>%
  group_by(class) %>%
  summarize(total = sum(bases)) %>%
  mutate(percent = (total/size)*100)



```





```{r fig.width=12, fig.height=4}


library(viridis)
count.data <- repeat_meta %>%
  arrange(desc(class)) %>%
  mutate(lab.ypos = cumsum(percent) - 0.5*percent) %>%
  mutate(percent = round(percent, digits = 2))
count.data

ggplot(count.data, aes(x = "", y = percent, fill = class)) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0)+
  geom_text(aes(y = lab.ypos, label = percent), color = "white")+
  #scale_fill_manual(values = mycols) +
  theme_void()+scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE) 

```

```{r reps, include=F}


reps <- repeats %>%
  mutate(X2 = (X2-1)) %>%
  separate(X5, c("class", "family"), sep =  "/") %>%
  mutate("family" = replace_na(family, "Unknown")) %>%
  dplyr::rename("repeat_type" = X4) %>%
  mutate(name = ifelse(family == c("centr"), paste0(class,"/",family),class)) %>%
  mutate(name = ifelse(family == c("telo"), paste0(class,"/",family),name)) %>%
  mutate(name = ifelse(family == c("acro"), paste0(class,"/",family),name)) %>%
  mutate(name = ifelse(family == c("subtelo"), paste0(class,"/",family),name)) %>%
  mutate(name = ifelse(name == c("Satellite"), repeat_type,name)) %>%
  mutate(name = ifelse(name == "Satellite/centr", repeat_type, name)) %>%
  mutate(name = ifelse(name == "DNA?", "DNA", name)) %>%
  mutate(name = ifelse(grepl("GSAT", repeat_type), "GSAT", name)) %>%
  mutate(name = ifelse(grepl("HSAT", repeat_type), "HSAT", name)) %>%
  mutate(name = ifelse(name == "Unspecified", "Unknown", name)) %>%
  mutate(name = ifelse(class == c("RC"), paste0(class,"/",family),name)) %>%
  mutate(name = as.factor(name)) %>%
  filter(X1 == "HiC_scaffold_18")



repeatColors =c("(CATTC)n" = "#E87C71",
    "(GAATC)n"="#E28455",
    "ALR/Alpha"="#D78C32",
    "BSR/Beta"="#E370AB",
    "CER" = "#CE9334",
    "DNA"="#C19935",
    "GSAT"="#B3A033",
    "HSAT"="#A2A638",
    "LINE"="#8CAC3E",
    "Low_complexity"="#75B042",
    "LSAU"="#54B346",
    "LTR"="#51B756",
    "RC/Helitron"="#53BB73",
    "Retroposon"="#55BE8D",
    "RNA"="#54C0A5",
    "rRNA"="#52BEBB",
    "SAR"="#51BDCE",
    "Satellite/acro"="#4EB8DF",
    "Satellite/telo"="#53B0E3",
    "SATR1"="#5AA5DA",
    "scRNA"="#6B9AD2",
    "Simple_repeat"="#8992C8",
    "SINE"="#9A8AC1",
    "snRNA"="#A885BC",
    "srpRNA"="#B67EB6",
    "SST1"="#C378B2",
    "Satellite/subtelo"="#D173AF",
    "tRNA"="#ED72A5",
    "Unknown"="#EF768C", 
    "(GAATG)n"="#ff4000",
    "D20S16" = "#ffbf00", 
   "SATR2"= "#0080ff" )

defaultColor = "#000080"


    

rep_leg <- ggplot(data=sat, mapping=aes(xmin=(X2),xmax=(X3),ymin=-1,ymax=1, fill = class))+
  geom_rect()  +  theme_void() +theme(legend.position="top") +labs(y="Axis")+theme(legend.text=element_text(size=rel(1.5)))+theme(legend.title=element_blank())

sat <- reps %>%
  filter(class == "Satellite")
rep_leg <- ggplot(data=sat, mapping=aes(xmin=(X2),xmax=(X3),ymin=-1,ymax=1, fill = class))+
  geom_rect()#+xlim(0,3000000)
print(rep_leg)
```

